//------------------------------------
// GOALS book
//
// Template for requirement:
//---- Requirement
//[[gx-keyword]] 
//`{counter:gx}`
// Requirement

// {missing} [Corresponding Artifact]
//---- 
//------------------------------------

== Goals

[NOTE]
====
Goals are "needs of the target organization, which the system will address". 
While the development team is the principal user of the other books, the Goals book addresses a wider audience: essentially, all stakeholders (see {Handbook}).

It must contain enough information to provide if read just by itself a general sketch of the entire project. 
To this effect, chapter G.3 presents a short overview of the system and <<G1,G.1>> will typically include some key properties of the environment. 
As it addresses a wide readership, it should be clear and minimize the use of specialized technical terms. 
Together, <<G1,G.1>>, <<G2,G.2>> and <<G3,G.3>> describe the rationale for the project. 
It is important to state these justifications explicitly. 
Typically, they are well understood at the start of the project, but management and priorities can change  (see {Handbook}).
====
